/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILocadora;

import SourceCodes.AutenticationCPF;
import SourceCodes.DBMetFuncionario;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Gian Luca
 */
public class Cad_FuncionarioJIF extends javax.swing.JInternalFrame {
    public String cod_escolha = null;
    /**
     * Creates new form Cad_FuncionarioJIF
     */
    public Cad_FuncionarioJIF() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc="Limite de Caracteres no TextField">
        jTXFNomeF.setDocument((Document) new CharacterLimit(100));
        jTXFIdentidadeF.setDocument((Document) new CharacterLimit(20));
        jTXFRuaF.setDocument((Document) new CharacterLimit(100));
        jTXFNumeroF.setDocument((Document) new CharacterLimit(8));
        jTXFComplementoF.setDocument((Document) new CharacterLimit(100));
        jTXFBairroF.setDocument((Document) new CharacterLimit(45));
        jTXFCidadeF.setDocument((Document) new CharacterLimit(45));
        jTXFEmailF.setDocument((Document) new CharacterLimit(45));
        jTXFLoginF.setDocument((Document) new CharacterLimit(20));
        jPTXFSenhaF.setDocument((Document) new CharacterLimit(10));
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFTFNascimentoF = new javax.swing.JFormattedTextField();
        jLBLNascimentoF = new javax.swing.JLabel();
        jTXFIdentidadeF = new javax.swing.JTextField();
        jLBLIdentidadeF = new javax.swing.JLabel();
        jFTFCPFF = new javax.swing.JFormattedTextField();
        jLBLCPFF = new javax.swing.JLabel();
        jLBLNomeF = new javax.swing.JLabel();
        jTXFNomeF = new javax.swing.JTextField();
        jLBLRuaF = new javax.swing.JLabel();
        jLBLNumeroF = new javax.swing.JLabel();
        jTXFNumeroF = new javax.swing.JTextField();
        jTXFRuaF = new javax.swing.JTextField();
        jFTFCEPF = new javax.swing.JFormattedTextField();
        jLBLCEPF = new javax.swing.JLabel();
        jTXFBairroF = new javax.swing.JTextField();
        jLBLCidadeF = new javax.swing.JLabel();
        jTXFCidadeF = new javax.swing.JTextField();
        jLBLComplementoF = new javax.swing.JLabel();
        jTXFComplementoF = new javax.swing.JTextField();
        jCBXEstadoF = new javax.swing.JComboBox();
        jLBLEstadoF = new javax.swing.JLabel();
        jFTFCelularF = new javax.swing.JFormattedTextField();
        jLBLCelularF = new javax.swing.JLabel();
        jFTFTelefoneF = new javax.swing.JFormattedTextField();
        jLBLTelefoneF = new javax.swing.JLabel();
        jLBLBairroF = new javax.swing.JLabel();
        jLBLEmailF = new javax.swing.JLabel();
        jTXFEmailF = new javax.swing.JTextField();
        jLBLCargoF = new javax.swing.JLabel();
        jCBXCargo = new javax.swing.JComboBox();
        jLBLLoginF = new javax.swing.JLabel();
        jTXFLoginF = new javax.swing.JTextField();
        jLBLSenhaF = new javax.swing.JLabel();
        jPTXFSenhaF = new javax.swing.JPasswordField();
        jPNLBotoesFunc = new javax.swing.JPanel();
        jBTNInserirFunc = new javax.swing.JButton();
        jBTNLimparFunc = new javax.swing.JButton();
        jBTNPesquisarFunc = new javax.swing.JButton();
        jBTNSair = new javax.swing.JButton();
        jBTNExcluir = new javax.swing.JButton();

        setTitle("Cadastro de Funcionários");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Obrigatórios"));

        jFTFNascimentoF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFNascimentoF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFNascimentoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLNascimentoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNascimentoF.setText("Nascimento:");

        jTXFIdentidadeF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFIdentidadeF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLIdentidadeF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLIdentidadeF.setText("Identidade:");

        jFTFCPFF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFCPFF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCPFF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFCPFF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFCPFFFocusLost(evt);
            }
        });

        jLBLCPFF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCPFF.setText("CPF:");

        jLBLNomeF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNomeF.setText("Nome:");
        jLBLNomeF.setToolTipText("");

        jTXFNomeF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFNomeF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTXFNomeF.setName(""); // NOI18N

        jLBLRuaF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLRuaF.setText("Endereço:");

        jLBLNumeroF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNumeroF.setText("Número:");

        jTXFNumeroF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFNumeroF.setToolTipText("");
        jTXFNumeroF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTXFRuaF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFRuaF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jFTFCEPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFCEPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCEPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLCEPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCEPF.setText("CEP:");

        jTXFBairroF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFBairroF.setToolTipText("");
        jTXFBairroF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLCidadeF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCidadeF.setText("Cidade:");

        jTXFCidadeF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFCidadeF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLComplementoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLComplementoF.setText("Complemento:");

        jTXFComplementoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFComplementoF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCBXEstadoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXEstadoF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCBXEstadoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBXEstadoFActionPerformed(evt);
            }
        });

        jLBLEstadoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLEstadoF.setText("Estado:");

        jFTFCelularF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFCelularF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCelularF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLCelularF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCelularF.setText("Celular:");

        jFTFTelefoneF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFTelefoneF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFTelefoneF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFTelefoneF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFTelefoneFActionPerformed(evt);
            }
        });

        jLBLTelefoneF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLTelefoneF.setText("Telefone:");

        jLBLBairroF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLBairroF.setText("Bairro:");

        jLBLEmailF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLEmailF.setText("E-Mail:");

        jTXFEmailF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFEmailF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLCargoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCargoF.setText("Cargo:");

        jCBXCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Funcionario" }));

        jLBLLoginF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLLoginF.setText("Login:");

        jTXFLoginF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFLoginF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLSenhaF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLSenhaF.setText("Senha:");

        jPTXFSenhaF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPTXFSenhaF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLTelefoneF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFTelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLCelularF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCelularF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLNumeroF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFNumeroF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLCEPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCEPF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLComplementoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFComplementoF)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLRuaF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFRuaF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLNomeF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFNomeF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLCPFF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCPFF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLIdentidadeF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFIdentidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLNascimentoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFNascimentoF))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLBairroF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFBairroF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLCidadeF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFCidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLEstadoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBXEstadoF, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 51, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLBLEmailF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFEmailF)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLBLLoginF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFLoginF)
                        .addGap(18, 18, 18)
                        .addComponent(jLBLSenhaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPTXFSenhaF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLBLCargoF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBXCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLNomeF)
                    .addComponent(jTXFNomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLCPFF)
                        .addComponent(jFTFCPFF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLIdentidadeF)
                        .addComponent(jTXFIdentidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLBLNascimentoF)
                        .addComponent(jFTFNascimentoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLRuaF)
                    .addComponent(jTXFRuaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTXFNumeroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLNumeroF)
                    .addComponent(jLBLCEPF)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFCEPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLComplementoF)
                        .addComponent(jTXFComplementoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBXEstadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLEstadoF)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLBLBairroF)
                            .addComponent(jTXFBairroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLBLCidadeF)
                            .addComponent(jTXFCidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLTelefoneF)
                    .addComponent(jFTFTelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLCelularF)
                    .addComponent(jFTFCelularF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLEmailF)
                    .addComponent(jTXFEmailF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBLCargoF)
                    .addComponent(jCBXCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLLoginF)
                        .addComponent(jTXFLoginF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLSenhaF)
                        .addComponent(jPTXFSenhaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPNLBotoesFunc.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNInserirFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Save.png"))); // NOI18N
        jBTNInserirFunc.setText("Salvar");
        jBTNInserirFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNInserirFuncMouseClicked(evt);
            }
        });

        jBTNLimparFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.png"))); // NOI18N
        jBTNLimparFunc.setText("Limpar");
        jBTNLimparFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNLimparFuncMouseClicked(evt);
            }
        });

        jBTNPesquisarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find.png"))); // NOI18N
        jBTNPesquisarFunc.setText("Pesquisar");
        jBTNPesquisarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNPesquisarFuncActionPerformed(evt);
            }
        });

        jBTNSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.png"))); // NOI18N
        jBTNSair.setText("Fechar");
        jBTNSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNSairMouseClicked(evt);
            }
        });

        jBTNExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        jBTNExcluir.setText("Excluir");
        jBTNExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNLBotoesFuncLayout = new javax.swing.GroupLayout(jPNLBotoesFunc);
        jPNLBotoesFunc.setLayout(jPNLBotoesFuncLayout);
        jPNLBotoesFuncLayout.setHorizontalGroup(
            jPNLBotoesFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNLBotoesFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTNInserirFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNLimparFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNPesquisarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPNLBotoesFuncLayout.setVerticalGroup(
            jPNLBotoesFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNLBotoesFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNLBotoesFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNInserirFunc)
                    .addComponent(jBTNLimparFunc)
                    .addComponent(jBTNPesquisarFunc)
                    .addComponent(jBTNSair)
                    .addComponent(jBTNExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPNLBotoesFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPNLBotoesFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBXEstadoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBXEstadoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBXEstadoFActionPerformed

    private void jFTFTelefoneFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFTelefoneFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFTelefoneFActionPerformed

    private void jBTNInserirFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNInserirFuncMouseClicked
        DBMetFuncionario DB_Func = new DBMetFuncionario();
        DB_Func.setNome(jTXFNomeF.getText());
        DB_Func.setCpf(jFTFCPFF.getText().replace("-", "").replace(".", ""));
        DB_Func.setIdentidade(jTXFIdentidadeF.getText());
        DB_Func.setNascimento(jFTFNascimentoF.getText());
        DB_Func.setEndereco(jTXFRuaF.getText());
        DB_Func.setNumero(jTXFNumeroF.getText());
        DB_Func.setComplemento(jTXFComplementoF.getText());
        DB_Func.setBairro(jTXFBairroF.getText());
        DB_Func.setCidade(jTXFCidadeF.getText());
        DB_Func.setCep(jFTFCEPF.getText().replace("-", ""));
        DB_Func.setEstado(jCBXEstadoF.getSelectedItem().toString());
        DB_Func.setTelefone(jFTFTelefoneF.getText());
        DB_Func.setCelular(jFTFCelularF.getText());
        DB_Func.setEmail(jTXFEmailF.getText());
        DB_Func.setCargo(jCBXCargo.getSelectedItem().toString());
        DB_Func.setLogin(jTXFLoginF.getText());
        DB_Func.setSenha(jPTXFSenhaF.getText());
        if (cod_escolha == null) {
            DB_Func.Cadastrar();
        } else {
            DB_Func.Alterar(cod_escolha);
        }

        jTXFNomeF.setText("");
        jFTFCPFF.setText("");
        jTXFIdentidadeF.setText("");
        jFTFNascimentoF.setText("");
        jTXFRuaF.setText("");
        jTXFNumeroF.setText("");
        jTXFComplementoF.setText("");
        jTXFBairroF.setText("");
        jFTFCEPF.setText("");
        jTXFCidadeF.setText("");
        jFTFTelefoneF.setText("");
        jFTFCelularF.setText("");
        jTXFEmailF.setText("");
        jTXFLoginF.setText("");
        jPTXFSenhaF.setText("");
        cod_escolha=null;
    }//GEN-LAST:event_jBTNInserirFuncMouseClicked

    private void jBTNLimparFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNLimparFuncMouseClicked
        jTXFNomeF.setText("");
        jFTFCPFF.setText("");
        jTXFIdentidadeF.setText("");
        jFTFNascimentoF.setText("");
        jTXFRuaF.setText("");
        jTXFNumeroF.setText("");
        jTXFComplementoF.setText("");
        jFTFCEPF.setText("");
        jTXFBairroF.setText("");
        jTXFCidadeF.setText("");
        jFTFTelefoneF.setText("");
        jFTFCelularF.setText("");
        jTXFEmailF.setText("");
        jTXFLoginF.setText("");
        jPTXFSenhaF.setText("");
        cod_escolha=null;
        jBTNInserirFunc.setText("Salvar");
    }//GEN-LAST:event_jBTNLimparFuncMouseClicked

    private void jBTNSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNSairMouseClicked
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "Sair da Tela", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBTNSairMouseClicked

    private void jFTFCPFFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFCPFFFocusLost
        AutenticationCPF autenticacao = new AutenticationCPF();
        autenticacao.MudarCaracter(jFTFCPFF.getText());
        if(autenticacao.ValidaCPF() == false)
        {
            JOptionPane.showMessageDialog(null, "CPF inválido.");
            jFTFCPFF.setText("");
        }
    }//GEN-LAST:event_jFTFCPFFFocusLost

    private void jBTNExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNExcluirActionPerformed
        cod_escolha = JOptionPane.showInputDialog("Digite o Código referente ao Funcioário que deseja excluir:").replace(".", "").replace("-", "");
        DBMetFuncionario Exc_Funcionario = new DBMetFuncionario();
        Exc_Funcionario.Exluir(cod_escolha);
    }//GEN-LAST:event_jBTNExcluirActionPerformed

    private void jBTNPesquisarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNPesquisarFuncActionPerformed
        cod_escolha = JOptionPane.showInputDialog("Digite o Código referente ao Funcionário que deseja pesquisar:").replace(".", "").replace("-", "");
        DBMetFuncionario Alterar = new DBMetFuncionario();
        Alterar.mostrar(cod_escolha);
        jTXFNomeF.setText(Alterar.getNome());
        jFTFCPFF.setText(Alterar.getCpf());
        jTXFIdentidadeF.setText(Alterar.getIdentidade());
        jFTFNascimentoF.setText(Alterar.getNascimento());
        jTXFRuaF.setText(Alterar.getEndereco());
        jTXFNumeroF.setText(Alterar.getNumero());
        jTXFComplementoF.setText(Alterar.getComplemento());
        jFTFCEPF.setText(Alterar.getCep());
        jTXFBairroF.setText(Alterar.getBairro());
        jTXFCidadeF.setText(Alterar.getCidade());
        jFTFTelefoneF.setText(Alterar.getTelefone());
        jFTFCelularF.setText(Alterar.getCelular());
        jTXFEmailF.setText(Alterar.getEmail());
        jTXFLoginF.setText(Alterar.getLogin());
        jPTXFSenhaF.setText(Alterar.getSenha());
        jCBXCargo.setSelectedItem(Alterar.getCargo());
        jCBXEstadoF.setSelectedItem(Alterar.getEstado());
        jBTNInserirFunc.setText("Alterar");
    }//GEN-LAST:event_jBTNPesquisarFuncActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNExcluir;
    private javax.swing.JButton jBTNInserirFunc;
    private javax.swing.JButton jBTNLimparFunc;
    private javax.swing.JButton jBTNPesquisarFunc;
    private javax.swing.JButton jBTNSair;
    private javax.swing.JComboBox jCBXCargo;
    private javax.swing.JComboBox jCBXEstadoF;
    private javax.swing.JFormattedTextField jFTFCEPF;
    private javax.swing.JFormattedTextField jFTFCPFF;
    private javax.swing.JFormattedTextField jFTFCelularF;
    private javax.swing.JFormattedTextField jFTFNascimentoF;
    private javax.swing.JFormattedTextField jFTFTelefoneF;
    private javax.swing.JLabel jLBLBairroF;
    private javax.swing.JLabel jLBLCEPF;
    private javax.swing.JLabel jLBLCPFF;
    private javax.swing.JLabel jLBLCargoF;
    private javax.swing.JLabel jLBLCelularF;
    private javax.swing.JLabel jLBLCidadeF;
    private javax.swing.JLabel jLBLComplementoF;
    private javax.swing.JLabel jLBLEmailF;
    private javax.swing.JLabel jLBLEstadoF;
    private javax.swing.JLabel jLBLIdentidadeF;
    private javax.swing.JLabel jLBLLoginF;
    private javax.swing.JLabel jLBLNascimentoF;
    private javax.swing.JLabel jLBLNomeF;
    private javax.swing.JLabel jLBLNumeroF;
    private javax.swing.JLabel jLBLRuaF;
    private javax.swing.JLabel jLBLSenhaF;
    private javax.swing.JLabel jLBLTelefoneF;
    private javax.swing.JPanel jPNLBotoesFunc;
    private javax.swing.JPasswordField jPTXFSenhaF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTXFBairroF;
    private javax.swing.JTextField jTXFCidadeF;
    private javax.swing.JTextField jTXFComplementoF;
    private javax.swing.JTextField jTXFEmailF;
    private javax.swing.JTextField jTXFIdentidadeF;
    private javax.swing.JTextField jTXFLoginF;
    private javax.swing.JTextField jTXFNomeF;
    private javax.swing.JTextField jTXFNumeroF;
    private javax.swing.JTextField jTXFRuaF;
    // End of variables declaration//GEN-END:variables
//<editor-fold defaultstate="collapsed" desc="Limite de Caracteres">

    public class CharacterLimit extends PlainDocument {

        private int iMaxLength;

        public CharacterLimit(int maxlen) {
            super();
            iMaxLength = maxlen;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {

            if (iMaxLength <= 0) // aceitara qualquer no. de caracteres  
            {
                super.insertString(offset, str, attr);
                return;
            }

            int ilen = (getLength() + str.length());
            if (ilen <= iMaxLength) // se o comprimento final for menor...  
            {
                super.insertString(offset, str, attr);   // ...aceita str  
            }
        }
    }
//</editor-fold>
}
