/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILocadora;

import SourceCodes.DBMetFilme;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Gian Luca
 */
public class Cad_FilmeJIF extends javax.swing.JInternalFrame {

    public int tipo_botao = 0;
    public String caminho = "", cod_escolha;

    /**
     * Creates new form Cad_FilmeJIF
     */
    public Cad_FilmeJIF() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc="Limite de Caracteres no TextField">
        jTXFCodigoF.setDocument((Document) new CharacterLimit(10));
        jTXFDiretorF.setDocument((Document) new CharacterLimit(100));
        jTXFDistribuidoraF.setDocument((Document) new CharacterLimit(100));
        jTXFQuantidadeF.setDocument((Document) new CharacterLimit(10));
        jTXFRoteiristaF.setDocument((Document) new CharacterLimit(100));
        jTXFTituloF.setDocument((Document) new CharacterLimit(100));
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPNObrigatoriosF = new javax.swing.JPanel();
        jTXFTituloF = new javax.swing.JTextField();
        jLBLTituloF = new javax.swing.JLabel();
        jLBLLancamentoF = new javax.swing.JLabel();
        jFTFLancamentoF = new javax.swing.JFormattedTextField();
        jLBLMidiaF = new javax.swing.JLabel();
        jCBXDiscoF = new javax.swing.JComboBox();
        jCBXGeneroF = new javax.swing.JComboBox();
        jLBLCategoriaF = new javax.swing.JLabel();
        jLBLDuracaoF = new javax.swing.JLabel();
        jFTFDuracaoF = new javax.swing.JFormattedTextField();
        jLBLCorF = new javax.swing.JLabel();
        jCBXCorF = new javax.swing.JComboBox();
        jCBXClassificacaoF = new javax.swing.JComboBox();
        jLBLClassificacaoF = new javax.swing.JLabel();
        jLBLCodigoF = new javax.swing.JLabel();
        jTXFCodigoF = new javax.swing.JTextField();
        jLBLQuantidadeF = new javax.swing.JLabel();
        jTXFQuantidadeF = new javax.swing.JTextField();
        jPNOpcionaisF = new javax.swing.JPanel();
        jTXFDiretorF = new javax.swing.JTextField();
        jLBLDiretorF = new javax.swing.JLabel();
        jLBLRoteiristaF = new javax.swing.JLabel();
        jTXFRoteiristaF = new javax.swing.JTextField();
        jLBLDistribuidoraF = new javax.swing.JLabel();
        jTXFDistribuidoraF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLBLPoster = new javax.swing.JLabel();
        jBTNInserir = new javax.swing.JButton();
        jPNBotoesF = new javax.swing.JPanel();
        jBTNSalvar = new javax.swing.JButton();
        jBTNLimpar = new javax.swing.JButton();
        jBTNSair = new javax.swing.JButton();
        jBTNPesquisar = new javax.swing.JButton();
        jBTNExcluir = new javax.swing.JButton();

        setTitle("Cadastro De Filmes");

        jPNObrigatoriosF.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Obrigatórios"));

        jTXFTituloF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTXFTituloF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLTituloF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLTituloF.setText("Título:");

        jLBLLancamentoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLLancamentoF.setText("Lançamento:");

        jFTFLancamentoF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFLancamentoF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFLancamentoF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLBLMidiaF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLMidiaF.setText("Disco:");

        jCBXDiscoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXDiscoF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blu-Ray", "DVD" }));
        jCBXDiscoF.setBorder(null);

        jCBXGeneroF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXGeneroF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Animação", "Adulto", "Ação", "Aventura", "Comédia", "Crime", "Drama", "Documentário", "Fantasia", "Guerra", "Ficção Científica", "Mistério", "Terror", "Horror" }));
        jCBXGeneroF.setBorder(null);

        jLBLCategoriaF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCategoriaF.setText("Gênero:");

        jLBLDuracaoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLDuracaoF.setText("Duração:");

        jFTFDuracaoF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFDuracaoF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### min")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFDuracaoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLCorF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCorF.setText("Cor:");

        jCBXCorF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXCorF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dourado", "Prata", "Azul", "Vermelho", "Branco" }));
        jCBXCorF.setBorder(null);

        jCBXClassificacaoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXClassificacaoF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Livre", "10+", "12+", "14+", "16+", "18+" }));
        jCBXClassificacaoF.setBorder(null);

        jLBLClassificacaoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLClassificacaoF.setText("Classificação:");

        jLBLCodigoF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCodigoF.setText("Código:");

        jTXFCodigoF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFCodigoF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLQuantidadeF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLQuantidadeF.setText("Quantidade:");

        jTXFQuantidadeF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFQuantidadeF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTXFQuantidadeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFQuantidadeFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNObrigatoriosFLayout = new javax.swing.GroupLayout(jPNObrigatoriosF);
        jPNObrigatoriosF.setLayout(jPNObrigatoriosFLayout);
        jPNObrigatoriosFLayout.setHorizontalGroup(
            jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                        .addComponent(jLBLCorF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBXCorF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLBLClassificacaoF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBXClassificacaoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                        .addComponent(jLBLCodigoF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLBLQuantidadeF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFQuantidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                        .addComponent(jLBLTituloF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFTituloF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNObrigatoriosFLayout.createSequentialGroup()
                        .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                                .addComponent(jLBLLancamentoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFLancamentoF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                                .addComponent(jLBLCategoriaF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBXGeneroF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                                .addComponent(jLBLMidiaF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBXDiscoF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                                .addComponent(jLBLDuracaoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFDuracaoF, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
        );
        jPNObrigatoriosFLayout.setVerticalGroup(
            jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNObrigatoriosFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLCodigoF)
                    .addComponent(jTXFCodigoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLQuantidadeF)
                    .addComponent(jTXFQuantidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTXFTituloF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLTituloF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPNObrigatoriosFLayout.createSequentialGroup()
                        .addComponent(jFTFLancamentoF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(jLBLLancamentoF)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLDuracaoF)
                        .addComponent(jFTFDuracaoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLMidiaF)
                        .addComponent(jCBXDiscoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLBLCategoriaF, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jCBXGeneroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLCorF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBXCorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNObrigatoriosFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLClassificacaoF)
                        .addComponent(jCBXClassificacaoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPNOpcionaisF.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Opcionais"));

        jTXFDiretorF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFDiretorF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLDiretorF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLDiretorF.setText("Diretor:");

        jLBLRoteiristaF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLRoteiristaF.setText("Roteirista:");

        jTXFRoteiristaF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFRoteiristaF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLDistribuidoraF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLDistribuidoraF.setText("Distribuidora:");

        jTXFDistribuidoraF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFDistribuidoraF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Capa:");

        jLBLPoster.setAutoscrolls(true);
        jLBLPoster.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNInserir.setText("Inserir");
        jBTNInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNInserirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPNOpcionaisFLayout = new javax.swing.GroupLayout(jPNOpcionaisF);
        jPNOpcionaisF.setLayout(jPNOpcionaisFLayout);
        jPNOpcionaisFLayout.setHorizontalGroup(
            jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                        .addComponent(jLBLDistribuidoraF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFDistribuidoraF, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                    .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                        .addComponent(jLBLRoteiristaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFRoteiristaF))
                    .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                        .addComponent(jLBLDiretorF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFDiretorF)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNOpcionaisFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBLPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNInserir)
                .addGap(136, 136, 136))
        );
        jPNOpcionaisFLayout.setVerticalGroup(
            jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                .addGroup(jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLDiretorF)
                    .addComponent(jTXFDiretorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXFRoteiristaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLRoteiristaF))
                .addGap(18, 18, 18)
                .addGroup(jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLDistribuidoraF)
                    .addComponent(jTXFDistribuidoraF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNOpcionaisFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPNOpcionaisFLayout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addComponent(jBTNInserir))
                    .addComponent(jLBLPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jPNBotoesF.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Save.png"))); // NOI18N
        jBTNSalvar.setText("Salvar");
        jBTNSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNSalvarMouseClicked(evt);
            }
        });
        jBTNSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNSalvarActionPerformed(evt);
            }
        });

        jBTNLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.png"))); // NOI18N
        jBTNLimpar.setText("Limpar");
        jBTNLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNLimparMouseClicked(evt);
            }
        });

        jBTNSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.png"))); // NOI18N
        jBTNSair.setText("Fechar");
        jBTNSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNSairMouseClicked(evt);
            }
        });

        jBTNPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find.png"))); // NOI18N
        jBTNPesquisar.setText("Pesquisar");
        jBTNPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNPesquisarMouseClicked(evt);
            }
        });

        jBTNExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        jBTNExcluir.setText("Excluir");
        jBTNExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPNBotoesFLayout = new javax.swing.GroupLayout(jPNBotoesF);
        jPNBotoesF.setLayout(jPNBotoesFLayout);
        jPNBotoesFLayout.setHorizontalGroup(
            jPNBotoesFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNBotoesFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTNSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTNSair)
                .addContainerGap())
        );
        jPNBotoesFLayout.setVerticalGroup(
            jPNBotoesFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNBotoesFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNBotoesFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNSalvar)
                    .addComponent(jBTNLimpar)
                    .addComponent(jBTNSair)
                    .addComponent(jBTNPesquisar)
                    .addComponent(jBTNExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPNBotoesF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPNOpcionaisF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPNObrigatoriosF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPNObrigatoriosF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPNOpcionaisF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPNBotoesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTXFQuantidadeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFQuantidadeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTXFQuantidadeFActionPerformed

    private void jBTNInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNInserirMouseClicked
        JFileChooser choose = new JFileChooser();
        choose.setFileFilter(new FileNameExtensionFilter("Imagem", "jpg", "jpeg", "gif", "png"));
        choose.setFileSelectionMode(JFileChooser.FILES_ONLY);
        choose.showDialog(choose, "Selecione");
        caminho = choose.getSelectedFile().getAbsolutePath();
        ImageIcon icon = new ImageIcon(caminho);
        if (icon.getIconWidth() < 130) {
            if (icon.getIconHeight() < 140) {
                jLBLPoster.setIcon(icon);
            }

        } else {
            icon.setImage(icon.getImage().getScaledInstance(130, 140, 100));
            jLBLPoster.setIcon(icon);
        }
    }//GEN-LAST:event_jBTNInserirMouseClicked

    private void jBTNSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNSalvarMouseClicked
        DBMetFilme Cad_Filme = new DBMetFilme();
        Cad_Filme.setCodigo(jTXFCodigoF.getText());
        Cad_Filme.setQuantidade(jTXFQuantidadeF.getText());
        Cad_Filme.setTitulo(jTXFTituloF.getText());
        Cad_Filme.setLancamento(jFTFLancamentoF.getText());
        Cad_Filme.setDuracao(jFTFDuracaoF.getText());
        Cad_Filme.setGenero(jCBXGeneroF.getSelectedItem().toString());
        Cad_Filme.setDisco(jCBXDiscoF.getSelectedItem().toString());
        Cad_Filme.setCor(jCBXCorF.getSelectedItem().toString());
        Cad_Filme.setClassificacao(jCBXClassificacaoF.getSelectedItem().toString());
        Cad_Filme.setRoteirista(jTXFRoteiristaF.getText());
        Cad_Filme.setDiretor(jTXFDiretorF.getText());
        Cad_Filme.setDistribuidora(jTXFDistribuidoraF.getText());
        Cad_Filme.setCapa(caminho.replace("\\", "¬"));
        JOptionPane.showMessageDialog(null, caminho);
        if (cod_escolha == null) {
            Cad_Filme.Cadastrar();
        } else {
            Cad_Filme.Alterar(cod_escolha);
        }
        jTXFCodigoF.setText("");
            jTXFDiretorF.setText("");
            jTXFDistribuidoraF.setText("");
            jTXFQuantidadeF.setText("");
            jTXFRoteiristaF.setText("");
            jTXFTituloF.setText("");
            jFTFDuracaoF.setText("");
            jFTFLancamentoF.setText("");
            jLBLPoster.setIcon(null);
            caminho = null;
    }//GEN-LAST:event_jBTNSalvarMouseClicked

    private void jBTNLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNLimparMouseClicked
        jTXFCodigoF.setText("");
        jTXFDiretorF.setText("");
        jTXFDistribuidoraF.setText("");
        jTXFQuantidadeF.setText("");
        jTXFRoteiristaF.setText("");
        jTXFTituloF.setText("");
        jFTFDuracaoF.setText("");
        jFTFLancamentoF.setText("");
        jLBLPoster.setIcon(null);
        caminho = null;
        jBTNSalvar.setText("Salvar");
    }//GEN-LAST:event_jBTNLimparMouseClicked

    @SuppressWarnings("empty-statement")
    private void jBTNSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNSairMouseClicked
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "Sair da Tela", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBTNSairMouseClicked

    private void jBTNExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNExcluirMouseClicked
        cod_escolha = JOptionPane.showInputDialog("Digite o Código referente ao Filme que deseja excluir:");
        DBMetFilme Exc_Filme = new DBMetFilme();
        Exc_Filme.Exluir(cod_escolha.trim());
    }//GEN-LAST:event_jBTNExcluirMouseClicked

    private void jBTNPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNPesquisarMouseClicked
        cod_escolha = JOptionPane.showInputDialog("Digite o Código referente ao Filme que deseja pesquisar:");
        DBMetFilme Alterar = new DBMetFilme();
        Alterar.mostrar(cod_escolha);
        jCBXCorF.setSelectedItem(Alterar.getCor());
        jCBXDiscoF.setSelectedItem(Alterar.getDisco());
        jCBXGeneroF.setSelectedItem(Alterar.getGenero());
        jCBXClassificacaoF.setSelectedItem(Alterar.getClassificacao());
        jFTFDuracaoF.setText(Alterar.getDuracao());
        jFTFLancamentoF.setText(Alterar.getLancamento());
        jTXFCodigoF.setText(Alterar.getCodigo());
        jTXFDiretorF.setText(Alterar.getDiretor());
        jTXFDistribuidoraF.setText(Alterar.getDistribuidora());
        jTXFQuantidadeF.setText(Alterar.getQuantidade());
        jTXFRoteiristaF.setText(Alterar.getRoteirista());
        jTXFTituloF.setText(Alterar.getTitulo());
        if (Alterar.getCapa() != null) {
            ImageIcon iconp = new ImageIcon(Alterar.getCapa().replace("¬", "\\"));
            caminho = Alterar.getCapa().replace("¬", "\\");
            JOptionPane.showMessageDialog(this, Alterar.getCapa());
            if (iconp.getIconWidth() < 130) {
                if (iconp.getIconHeight() < 140) {
                    jLBLPoster.setIcon(iconp);
                }

            } else {
                iconp.setImage(iconp.getImage().getScaledInstance(130, 140, 100));
                jLBLPoster.setIcon(iconp);
            }
        }
        jBTNSalvar.setText("Alterar");
    }//GEN-LAST:event_jBTNPesquisarMouseClicked

    private void jBTNSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTNSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNExcluir;
    private javax.swing.JButton jBTNInserir;
    private javax.swing.JButton jBTNLimpar;
    private javax.swing.JButton jBTNPesquisar;
    private javax.swing.JButton jBTNSair;
    private javax.swing.JButton jBTNSalvar;
    private javax.swing.JComboBox jCBXClassificacaoF;
    private javax.swing.JComboBox jCBXCorF;
    private javax.swing.JComboBox jCBXDiscoF;
    private javax.swing.JComboBox jCBXGeneroF;
    private javax.swing.JFormattedTextField jFTFDuracaoF;
    private javax.swing.JFormattedTextField jFTFLancamentoF;
    private javax.swing.JLabel jLBLCategoriaF;
    private javax.swing.JLabel jLBLClassificacaoF;
    private javax.swing.JLabel jLBLCodigoF;
    private javax.swing.JLabel jLBLCorF;
    private javax.swing.JLabel jLBLDiretorF;
    private javax.swing.JLabel jLBLDistribuidoraF;
    private javax.swing.JLabel jLBLDuracaoF;
    private javax.swing.JLabel jLBLLancamentoF;
    private javax.swing.JLabel jLBLMidiaF;
    private javax.swing.JLabel jLBLPoster;
    private javax.swing.JLabel jLBLQuantidadeF;
    private javax.swing.JLabel jLBLRoteiristaF;
    private javax.swing.JLabel jLBLTituloF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPNBotoesF;
    private javax.swing.JPanel jPNObrigatoriosF;
    private javax.swing.JPanel jPNOpcionaisF;
    private javax.swing.JTextField jTXFCodigoF;
    private javax.swing.JTextField jTXFDiretorF;
    private javax.swing.JTextField jTXFDistribuidoraF;
    private javax.swing.JTextField jTXFQuantidadeF;
    private javax.swing.JTextField jTXFRoteiristaF;
    private javax.swing.JTextField jTXFTituloF;
    // End of variables declaration//GEN-END:variables
//<editor-fold defaultstate="collapsed" desc="Limite de Caracteres">

    public class CharacterLimit extends PlainDocument {

        private int iMaxLength;

        public CharacterLimit(int maxlen) {
            super();
            iMaxLength = maxlen;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {

            if (iMaxLength <= 0) // aceitara qualquer no. de caracteres  
            {
                super.insertString(offset, str, attr);
                return;
            }

            int ilen = (getLength() + str.length());
            if (ilen <= iMaxLength) // se o comprimento final for menor...  
            {
                super.insertString(offset, str, attr);   // ...aceita str  
            }
        }
    }
//</editor-fold>
}
