/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILocadora;

import SourceCodes.AutenticationCPF;
import SourceCodes.DBMetClientes;
import SourceCodes.DBMetFilme;
import SourceCodes.Reserva;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Gian Luca
 */
public class Cad_ReservaJIF extends javax.swing.JInternalFrame {

    ArrayList<String> codigofilme;
    float valor = 0;
    int idreserva = 0, a = 0;
    int i;
    String valor2 = null;
    String idreserva2;

    /**
     * Creates new form ReservaJIF
     */
    public Cad_ReservaJIF() {
        initComponents();
        codigofilme = new ArrayList();
        //<editor-fold defaultstate="collapsed" desc="Limite de Caracteres no TextField">
        jTXFIDFilmeR.setDocument((Document) new Cad_ReservaJIF.CharacterLimit(10));
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPNClienteR = new javax.swing.JPanel();
        jBTNPesquisarR = new javax.swing.JButton();
        jFTFCPFR = new javax.swing.JFormattedTextField();
        jLBLCPFR = new javax.swing.JLabel();
        jLBLNomeR = new javax.swing.JLabel();
        jTXFNomeR = new javax.swing.JTextField();
        jLBLTelefoneR = new javax.swing.JLabel();
        jFTFTelefoneR = new javax.swing.JFormattedTextField();
        jLBLCelularR = new javax.swing.JLabel();
        jFTFCelularR = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jBTNPesquisarP1 = new javax.swing.JButton();
        jTXFIDFilmeR = new javax.swing.JTextField();
        jLBLCodigoP = new javax.swing.JLabel();
        jTXFTituloR = new javax.swing.JTextField();
        jLBLTituloR = new javax.swing.JLabel();
        jLBLMidiaR = new javax.swing.JLabel();
        jTXFMidiaR = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLBLValorR = new javax.swing.JLabel();
        jFTFValorR = new javax.swing.JFormattedTextField();
        jLBLReserva = new javax.swing.JLabel();
        jFTFReservaR = new javax.swing.JFormattedTextField();
        jLBLReservaNumero = new javax.swing.JLabel();
        jTXFReservaID = new javax.swing.JTextField();
        jFTFBuscaR = new javax.swing.JFormattedTextField();
        jLBLBuscaR = new javax.swing.JLabel();
        jLBLFilme1 = new javax.swing.JLabel();
        jLBLFilme2 = new javax.swing.JLabel();
        jLBLFilme3 = new javax.swing.JLabel();
        jLBLNomeFilme1 = new javax.swing.JLabel();
        jLBLNomeFilme2 = new javax.swing.JLabel();
        jLBLNomeFilme3 = new javax.swing.JLabel();
        jLBLMidia1 = new javax.swing.JLabel();
        jLBLMidia3 = new javax.swing.JLabel();
        jLBLMidia2 = new javax.swing.JLabel();
        jLBLMidiaNome1 = new javax.swing.JLabel();
        jLBLMidiaNome2 = new javax.swing.JLabel();
        jLBLMidiaNome3 = new javax.swing.JLabel();
        jLBLStatus = new javax.swing.JLabel();
        jTXFStatus = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBTNSalvar = new javax.swing.JButton();
        jBTNLimpar = new javax.swing.JButton();
        jBTNPesquisar = new javax.swing.JButton();
        jBTNExcluir = new javax.swing.JButton();
        jBTNSair = new javax.swing.JButton();

        setTitle("Reserva");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        JPNClienteR.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNPesquisarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find 16x16.png"))); // NOI18N
        jBTNPesquisarR.setText("Pesquisar");
        jBTNPesquisarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNPesquisarRActionPerformed(evt);
            }
        });

        try {
            jFTFCPFR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCPFR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFCPFRFocusLost(evt);
            }
        });

        jLBLCPFR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCPFR.setText("CPF:");

        jLBLNomeR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNomeR.setText("Nome:");

        jTXFNomeR.setEditable(false);
        jTXFNomeR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLTelefoneR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLTelefoneR.setText("Telefone:");

        jFTFTelefoneR.setEditable(false);
        try {
            jFTFTelefoneR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFTelefoneR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLCelularR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCelularR.setText("Celular:");

        jFTFCelularR.setEditable(false);
        try {
            jFTFCelularR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCelularR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout JPNClienteRLayout = new javax.swing.GroupLayout(JPNClienteR);
        JPNClienteR.setLayout(JPNClienteRLayout);
        JPNClienteRLayout.setHorizontalGroup(
            JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNClienteRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNClienteRLayout.createSequentialGroup()
                        .addComponent(jLBLNomeR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFNomeR))
                    .addGroup(JPNClienteRLayout.createSequentialGroup()
                        .addComponent(jLBLCPFR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFCPFR, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTNPesquisarR))
                    .addGroup(JPNClienteRLayout.createSequentialGroup()
                        .addComponent(jLBLTelefoneR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFTelefoneR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jLBLCelularR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFCelularR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPNClienteRLayout.setVerticalGroup(
            JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNClienteRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFCPFR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBTNPesquisarR))
                    .addComponent(jLBLCPFR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTXFNomeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLNomeR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBLTelefoneR)
                    .addComponent(jFTFTelefoneR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPNClienteRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFCelularR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLCelularR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNPesquisarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find 16x16.png"))); // NOI18N
        jBTNPesquisarP1.setText("Pesquisar");
        jBTNPesquisarP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNPesquisarP1MouseClicked(evt);
            }
        });
        jBTNPesquisarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNPesquisarP1ActionPerformed(evt);
            }
        });
        jBTNPesquisarP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBTNPesquisarP1KeyPressed(evt);
            }
        });

        jTXFIDFilmeR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLCodigoP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCodigoP.setText("Código Do Filme:");

        jTXFTituloR.setEditable(false);
        jTXFTituloR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLTituloR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLTituloR.setText("Título:");

        jLBLMidiaR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLMidiaR.setText("Mídia:");

        jTXFMidiaR.setEditable(false);
        jTXFMidiaR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFMidiaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFMidiaRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLBLTituloR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFTituloR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLCodigoP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFIDFilmeR, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBTNPesquisarP1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLBLMidiaR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFMidiaR, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLCodigoP)
                    .addComponent(jTXFIDFilmeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTNPesquisarP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLTituloR)
                    .addComponent(jTXFTituloR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLMidiaR)
                    .addComponent(jTXFMidiaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLBLValorR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLValorR.setText("Valor à Pagar:");

        jFTFValorR.setEditable(false);
        try {
            jFTFValorR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFValorR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLReserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLReserva.setText("Data de Reserva:");

        try {
            jFTFReservaR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFReservaR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLReservaNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLReservaNumero.setText("Reserva de Nº:");

        jTXFReservaID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            jFTFBuscaR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFBuscaR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLBuscaR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLBuscaR.setText("Data de Busca:");

        jLBLFilme1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLFilme1.setText("Filme 1:");

        jLBLFilme2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLFilme2.setText("Filme 2:");

        jLBLFilme3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLFilme3.setText("Filme 3:");

        jLBLNomeFilme1.setText("Nome filme aqui");

        jLBLNomeFilme2.setText("Nome filme aqui");

        jLBLNomeFilme3.setText("Nome filme aqui");

        jLBLMidia1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLMidia1.setText("Midia:");

        jLBLMidia3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLMidia3.setText("Midia:");

        jLBLMidia2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLMidia2.setText("Midia:");

        jLBLMidiaNome1.setText("dvd");

        jLBLMidiaNome2.setText("dvd");

        jLBLMidiaNome3.setText("dvd");

        jLBLStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLStatus.setText("Status");

        jTXFStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLBLValorR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFValorR, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLBLBuscaR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFBuscaR, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLBLStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFStatus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLBLReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFReservaR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLBLReservaNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFReservaID))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLFilme2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLNomeFilme2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLFilme3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLNomeFilme3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLFilme1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLNomeFilme1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLMidia3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLMidiaNome3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLMidia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLMidiaNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLMidia2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLMidiaNome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFReservaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLReserva)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTXFReservaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLReservaNumero)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLFilme1)
                    .addComponent(jLBLNomeFilme1)
                    .addComponent(jLBLMidia1)
                    .addComponent(jLBLMidiaNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLFilme2)
                    .addComponent(jLBLNomeFilme2)
                    .addComponent(jLBLMidia2)
                    .addComponent(jLBLMidiaNome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLFilme3)
                    .addComponent(jLBLNomeFilme3)
                    .addComponent(jLBLMidia3)
                    .addComponent(jLBLMidiaNome3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLValorR)
                    .addComponent(jFTFValorR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLBuscaR)
                        .addComponent(jFTFBuscaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLStatus)
                        .addComponent(jTXFStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Save.png"))); // NOI18N
        jBTNSalvar.setText("Salvar");
        jBTNSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNSalvarActionPerformed(evt);
            }
        });

        jBTNLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.png"))); // NOI18N
        jBTNLimpar.setText("Limpar");
        jBTNLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNLimparMouseClicked(evt);
            }
        });

        jBTNPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find.png"))); // NOI18N
        jBTNPesquisar.setText("Pesquisar");

        jBTNExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        jBTNExcluir.setText("Excluir");

        jBTNSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.png"))); // NOI18N
        jBTNSair.setText("Fechar");
        jBTNSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTNSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNSalvar)
                    .addComponent(jBTNLimpar)
                    .addComponent(jBTNPesquisar)
                    .addComponent(jBTNExcluir)
                    .addComponent(jBTNSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPNClienteR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JPNClienteR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(556, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTNPesquisarP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNPesquisarP1MouseClicked

    }//GEN-LAST:event_jBTNPesquisarP1MouseClicked

    private void jBTNPesquisarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNPesquisarP1ActionPerformed
        
        
        for (i = 0; i < 3; i++) {
            codigofilme.add(i, jTXFIDFilmeR.getText());
            break;
        }
        DBMetFilme filme = new DBMetFilme();
        filme.mostrar(jTXFIDFilmeR.getText());
        jTXFTituloR.setText(filme.getTitulo());
        jTXFMidiaR.setText(filme.getDisco());
        if (filme.getCodigo()!= null) {
            a = a + 1;
            System.out.print(a);
        }

        switch (a) {
            case 1:
                jLBLNomeFilme1.setText(filme.getTitulo());
                jLBLMidiaNome1.setText(filme.getDisco());
                //<editor-fold defaultstate="colapsed" desc="Calculo de valor">
                if ("Dourado".equals(filme.getCor())) {
                    valor += 05.00;
                } else {
                    if ("Prata".equals(filme.getCor())) {
                        valor += 04.00;
                    } else {
                        if ("Azul".equals(filme.getCor())) {
                            valor += 03.00;
                        } else {
                            if ("Vermelho".equals(filme.getCor())) {
                                valor += 02.00;
                            } else {
                                if ("Branco".equals(filme.getCor())) {
                                    valor += 01.00;
                                }
                            }
                        }
                    }
                }
                //</editor-fold>
                //<editor-fold defaultstate="colapsed" desc="Calculo de valor">
                if ("DVD".equals(filme.getDisco())) {
                    valor += 20.00;
                } else {
                    if ("Blu-Ray".equals(filme.getDisco())) {
                        valor += 30.00;
                    }
                }
                //</editor-fold>
                break;
            case 2:
                jLBLNomeFilme2.setText(filme.getTitulo());
                jLBLMidiaNome2.setText(filme.getDisco());
                //<editor-fold defaultstate="colapsed" desc="Calculo de valor">
                if ("Dourado".equals(filme.getCor())) {
                    valor += 05.00;
                } else {
                    if ("Prata".equals(filme.getCor())) {
                        valor += 04.00;
                    } else {
                        if ("Azul".equals(filme.getCor())) {
                            valor += 03.00;
                        } else {
                            if ("Vermelho".equals(filme.getCor())) {
                                valor += 02.00;
                            } else {
                                if ("Branco".equals(filme.getCor())) {
                                    valor += 01.00;
                                }
                            }
                        }
                    }
                }
                //</editor-fold>
                //<editor-fold defaultstate="colapsed" desc="Calculo de valor">
                if ("DVD".equals(filme.getDisco())) {
                    valor += 20.00;
                } else {
                    if ("Blu-Ray".equals(filme.getDisco())) {
                        valor += 30.00;
                    }
                }
                //</editor-fold>
                break;
            case 3:
                jLBLNomeFilme3.setText(filme.getTitulo());
                jLBLMidiaNome3.setText(filme.getDisco());
                //<editor-fold defaultstate="colapsed" desc="Calculo de valor">
                if ("Dourado".equals(filme.getCor())) {
                    valor += 05.00;
                } else {
                    if ("Prata".equals(filme.getCor())) {
                        valor += 04.00;
                    } else {
                        if ("Azul".equals(filme.getCor())) {
                            valor += 03.00;
                        } else {
                            if ("Vermelho".equals(filme.getCor())) {
                                valor += 02.00;
                            } else {
                                if ("Branco".equals(filme.getCor())) {
                                    valor += 01.00;
                                }
                            }
                        }
                    }
                }
                //</editor-fold>
                //<editor-fold defaultstate="colapsed" desc="Calculo de valor">
                if ("DVD".equals(filme.getDisco())) {
                    valor += 20.00;
                } else {
                    if ("Blu-Ray".equals(filme.getDisco())) {
                        valor += 30.00;
                    }
                }
                //</editor-fold>
                break;
        }
        valor2 = String.valueOf(valor);
        jFTFValorR.setText(valor2.replace(".", ","));
    }//GEN-LAST:event_jBTNPesquisarP1ActionPerformed

    private void jBTNPesquisarP1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBTNPesquisarP1KeyPressed

    }//GEN-LAST:event_jBTNPesquisarP1KeyPressed

    private void jTXFMidiaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFMidiaRActionPerformed

    }//GEN-LAST:event_jTXFMidiaRActionPerformed

    private void jBTNSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNSairMouseClicked
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "Sair da Tela", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBTNSairMouseClicked

    private void jBTNLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNLimparMouseClicked
        jTXFNomeR.setText("");
        jFTFBuscaR.setText("");
        jFTFCPFR.setText("");
        jFTFCelularR.setText("");
        jFTFReservaR.setText("");
        jFTFTelefoneR.setText("");
        jFTFValorR.setText("");
        jLBLMidiaNome1.setText("");
        jLBLMidiaNome2.setText("");
        jLBLMidiaNome3.setText("");
        jLBLNomeFilme1.setText("");
        jLBLNomeFilme2.setText("");
        jLBLNomeFilme3.setText("");
        jTXFIDFilmeR.setText("");
        jTXFMidiaR.setText("");
        jTXFReservaID.setText("");
        jTXFTituloR.setText("");
        jTXFStatus.setText("");
        i = 0;
        valor = 0;
        a = 0;
        valor2 = null;
        for (i = 0; i < 3; i++) {
            System.out.println(codigofilme.get(i));
        }
        idreserva2 = String.valueOf(idreserva);
        jTXFReservaID.setText(idreserva2);
    }//GEN-LAST:event_jBTNLimparMouseClicked

    private void jFTFCPFRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFCPFRFocusLost
        AutenticationCPF autenticacao = new AutenticationCPF();
        autenticacao.MudarCaracter(jFTFCPFR.getText());
        if (autenticacao.ValidaCPF() == false) {
            JOptionPane.showMessageDialog(null, "CPF inválido.");
            jFTFCPFR.setText("");
        }
    }//GEN-LAST:event_jFTFCPFRFocusLost

    private void jBTNSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNSalvarActionPerformed
        Reserva cadastro = new Reserva();
        cadastro.setCpf(jFTFCPFR.getText().replace("-", "").replace(".", ""));
        cadastro.setCodigoFilme(codigofilme);
        cadastro.setValor(valor);
        cadastro.setDataBusca(title);
        cadastro.setDataReserva(title);
        cadastro.setStatus(jTXFStatus.getText());
        cadastro.setIdReserva(idreserva);
        cadastro.Cadastrar();
        idreserva = idreserva+1;
        idreserva2 = String.valueOf(idreserva);
        jTXFReservaID.setText(idreserva2);
    }//GEN-LAST:event_jBTNSalvarActionPerformed

    private void jBTNPesquisarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNPesquisarRActionPerformed
        DBMetClientes cliente = new DBMetClientes();
        cliente.mostrar(jFTFCPFR.getText().replace("-", "").replace(".", ""));
        jTXFNomeR.setText(cliente.getNome());
        jFTFTelefoneR.setText(cliente.getTelefone());
        jFTFCelularR.setText(cliente.getCelular());
    }//GEN-LAST:event_jBTNPesquisarRActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
                
        idreserva = idreserva+1;
        idreserva2 = String.valueOf(idreserva);
        jTXFReservaID.setText(idreserva2);
        
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPNClienteR;
    private javax.swing.JButton jBTNExcluir;
    private javax.swing.JButton jBTNLimpar;
    private javax.swing.JButton jBTNPesquisar;
    private javax.swing.JButton jBTNPesquisarP1;
    private javax.swing.JButton jBTNPesquisarR;
    private javax.swing.JButton jBTNSair;
    private javax.swing.JButton jBTNSalvar;
    private javax.swing.JFormattedTextField jFTFBuscaR;
    private javax.swing.JFormattedTextField jFTFCPFR;
    private javax.swing.JFormattedTextField jFTFCelularR;
    private javax.swing.JFormattedTextField jFTFReservaR;
    private javax.swing.JFormattedTextField jFTFTelefoneR;
    private javax.swing.JFormattedTextField jFTFValorR;
    private javax.swing.JLabel jLBLBuscaR;
    private javax.swing.JLabel jLBLCPFR;
    private javax.swing.JLabel jLBLCelularR;
    private javax.swing.JLabel jLBLCodigoP;
    private javax.swing.JLabel jLBLFilme1;
    private javax.swing.JLabel jLBLFilme2;
    private javax.swing.JLabel jLBLFilme3;
    private javax.swing.JLabel jLBLMidia1;
    private javax.swing.JLabel jLBLMidia2;
    private javax.swing.JLabel jLBLMidia3;
    private javax.swing.JLabel jLBLMidiaNome1;
    private javax.swing.JLabel jLBLMidiaNome2;
    private javax.swing.JLabel jLBLMidiaNome3;
    private javax.swing.JLabel jLBLMidiaR;
    private javax.swing.JLabel jLBLNomeFilme1;
    private javax.swing.JLabel jLBLNomeFilme2;
    private javax.swing.JLabel jLBLNomeFilme3;
    private javax.swing.JLabel jLBLNomeR;
    private javax.swing.JLabel jLBLReserva;
    private javax.swing.JLabel jLBLReservaNumero;
    private javax.swing.JLabel jLBLStatus;
    private javax.swing.JLabel jLBLTelefoneR;
    private javax.swing.JLabel jLBLTituloR;
    private javax.swing.JLabel jLBLValorR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTXFIDFilmeR;
    private javax.swing.JTextField jTXFMidiaR;
    private javax.swing.JTextField jTXFNomeR;
    private javax.swing.JTextField jTXFReservaID;
    private javax.swing.JTextField jTXFStatus;
    private javax.swing.JTextField jTXFTituloR;
    // End of variables declaration//GEN-END:variables
//<editor-fold defaultstate="collapsed" desc="Limite de Caracteres">

    public class CharacterLimit extends PlainDocument {

        private int iMaxLength;

        public CharacterLimit(int maxlen) {
            super();
            iMaxLength = maxlen;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {

            if (iMaxLength <= 0) // aceitara qualquer no. de caracteres  
            {
                super.insertString(offset, str, attr);
                return;
            }

            int ilen = (getLength() + str.length());
            if (ilen <= iMaxLength) // se o comprimento final for menor...  
            {
                super.insertString(offset, str, attr);   // ...aceita str  
            }
        }
    }
//</editor-fold>
}
