/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILocadora;

import SourceCodes.AutenticationCPF;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Gian Luca
 */
public class Cad_PedidoJIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidoJIF
     */
    public Cad_PedidoJIF() {
        initComponents();
        //<editor-fold defaultstate="collapsed" desc="Limite de Caracteres no TextField">
        jTXFIDFilmeP.setDocument((Document) new Cad_PedidoJIF.CharacterLimit(10));
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLBLCPFP = new javax.swing.JLabel();
        jFTFCPFP = new javax.swing.JFormattedTextField();
        jBTNPesquisarP = new javax.swing.JButton();
        jLBLNomeP = new javax.swing.JLabel();
        jTXFNomeP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLBLCodigoP = new javax.swing.JLabel();
        jTXFIDFilmeP = new javax.swing.JTextField();
        jLBLTituloP = new javax.swing.JLabel();
        jTXFTituloP = new javax.swing.JTextField();
        jBTNPesquisarP1 = new javax.swing.JButton();
        jLBLMidiaP = new javax.swing.JLabel();
        jTXFMidia = new javax.swing.JTextField();
        jLBLCorP = new javax.swing.JLabel();
        jTXFCorP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLBLLocacao = new javax.swing.JLabel();
        jFTFLocacaoP = new javax.swing.JFormattedTextField();
        jLBLEntregaP = new javax.swing.JLabel();
        jFTFEntregaP = new javax.swing.JFormattedTextField();
        jLBLQuantidadeP = new javax.swing.JLabel();
        jTXFQuantidadeP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBFilmesP = new javax.swing.JTable();
        jLBLValorP = new javax.swing.JLabel();
        jFTFValorP = new javax.swing.JFormattedTextField();
        jLBLIDPedido = new javax.swing.JLabel();
        jTXFPedidoID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBTNSalvar = new javax.swing.JButton();
        jBTNLimpar = new javax.swing.JButton();
        jBTNPesquisar = new javax.swing.JButton();
        jBTNExcluir = new javax.swing.JButton();
        jBTNSair = new javax.swing.JButton();

        setTitle("Pedidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLBLCPFP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCPFP.setText("CPF:");

        try {
            jFTFCPFP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCPFP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFCPFPFocusLost(evt);
            }
        });

        jBTNPesquisarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find 16x16.png"))); // NOI18N
        jBTNPesquisarP.setText("Pesquisar");

        jLBLNomeP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNomeP.setText("Nome:");

        jTXFNomeP.setEditable(false);
        jTXFNomeP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLBLNomeP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFNomeP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLBLCPFP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFCPFP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTNPesquisarP)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFCPFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBTNPesquisarP))
                    .addComponent(jLBLCPFP))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTXFNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLNomeP))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLBLCodigoP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCodigoP.setText("Código Do Filme:");

        jTXFIDFilmeP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLTituloP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLTituloP.setText("Título:");

        jTXFTituloP.setEditable(false);
        jTXFTituloP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBTNPesquisarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find 16x16.png"))); // NOI18N
        jBTNPesquisarP1.setText("Pesquisar");
        jBTNPesquisarP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNPesquisarP1MouseClicked(evt);
            }
        });
        jBTNPesquisarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNPesquisarP1ActionPerformed(evt);
            }
        });
        jBTNPesquisarP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBTNPesquisarP1KeyPressed(evt);
            }
        });

        jLBLMidiaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLMidiaP.setText("Mídia:");

        jTXFMidia.setEditable(false);
        jTXFMidia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFMidia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXFMidiaActionPerformed(evt);
            }
        });

        jLBLCorP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCorP.setText("Cor:");

        jTXFCorP.setEditable(false);
        jTXFCorP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLBLTituloP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFTituloP))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLMidiaP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLBLCorP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFCorP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLBLCodigoP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFIDFilmeP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBTNPesquisarP1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLCodigoP)
                    .addComponent(jTXFIDFilmeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTNPesquisarP1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLTituloP)
                    .addComponent(jTXFTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLMidiaP)
                        .addComponent(jTXFMidia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLCorP))
                    .addComponent(jTXFCorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLBLLocacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLLocacao.setText("Data de Locação:");

        try {
            jFTFLocacaoP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFLocacaoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLEntregaP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLEntregaP.setText("Data de Entrega:");

        try {
            jFTFEntregaP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFEntregaP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLQuantidadeP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLQuantidadeP.setText("Quantidade:");

        jTXFQuantidadeP.setEditable(false);
        jTXFQuantidadeP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTBFilmesP.setAutoCreateRowSorter(true);
        jTBFilmesP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTBFilmesP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Filmes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBFilmesP.setFocusable(false);
        jTBFilmesP.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTBFilmesP);

        jLBLValorP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLValorP.setText("Valor à Pagar:");

        jFTFValorP.setEditable(false);
        try {
            jFTFValorP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFValorP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLIDPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLIDPedido.setText("Pedido de Nº:");

        jTXFPedidoID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLBLValorP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLBLEntregaP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFEntregaP))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLBLLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFLocacaoP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLBLQuantidadeP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFQuantidadeP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLBLIDPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFPedidoID, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFLocacaoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLLocacao)
                    .addComponent(jLBLQuantidadeP)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTXFQuantidadeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLIDPedido))
                    .addComponent(jTXFPedidoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFTFEntregaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLEntregaP))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLValorP)
                        .addComponent(jFTFValorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Save.png"))); // NOI18N
        jBTNSalvar.setText("Salvar");

        jBTNLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.png"))); // NOI18N
        jBTNLimpar.setText("Limpar");
        jBTNLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNLimparMouseClicked(evt);
            }
        });

        jBTNPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find.png"))); // NOI18N
        jBTNPesquisar.setText("Pesquisar");

        jBTNExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        jBTNExcluir.setText("Excluir");

        jBTNSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.png"))); // NOI18N
        jBTNSair.setText("Fechar");
        jBTNSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTNSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNSalvar)
                    .addComponent(jBTNLimpar)
                    .addComponent(jBTNPesquisar)
                    .addComponent(jBTNExcluir)
                    .addComponent(jBTNSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTNPesquisarP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNPesquisarP1MouseClicked
        jTXFMidia.setText("Olá jovem");
    }//GEN-LAST:event_jBTNPesquisarP1MouseClicked

    private void jBTNPesquisarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNPesquisarP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTNPesquisarP1ActionPerformed

    private void jBTNPesquisarP1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBTNPesquisarP1KeyPressed

    }//GEN-LAST:event_jBTNPesquisarP1KeyPressed

    private void jTXFMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXFMidiaActionPerformed

    }//GEN-LAST:event_jTXFMidiaActionPerformed

    private void jBTNSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNSairMouseClicked
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "Sair da Tela", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBTNSairMouseClicked

    private void jBTNLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNLimparMouseClicked
        jFTFCPFP.setText("");
    jFTFEntregaP.setText("");
    jFTFLocacaoP.setText("");;
    jFTFValorP.setText("");
    jTXFCorP.setText("");
    jTXFIDFilmeP.setText("");
    jTXFMidia.setText("");
    jTXFNomeP.setText("");
    jTXFPedidoID.setText("");
    jTXFQuantidadeP.setText("");
    jTXFTituloP.setText("");
    jScrollPane1.removeAll();
    jTBFilmesP.removeAll();
    }//GEN-LAST:event_jBTNLimparMouseClicked

    private void jFTFCPFPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFCPFPFocusLost
        AutenticationCPF autenticacao = new AutenticationCPF();
        autenticacao.MudarCaracter(jFTFCPFP.getText());
        if(autenticacao.ValidaCPF() == false)
        {
            JOptionPane.showMessageDialog(null, "CPF inválido.");
            jFTFCPFP.setText("");
        }
    }//GEN-LAST:event_jFTFCPFPFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNExcluir;
    private javax.swing.JButton jBTNLimpar;
    private javax.swing.JButton jBTNPesquisar;
    private javax.swing.JButton jBTNPesquisarP;
    private javax.swing.JButton jBTNPesquisarP1;
    private javax.swing.JButton jBTNSair;
    private javax.swing.JButton jBTNSalvar;
    private javax.swing.JFormattedTextField jFTFCPFP;
    private javax.swing.JFormattedTextField jFTFEntregaP;
    private javax.swing.JFormattedTextField jFTFLocacaoP;
    private javax.swing.JFormattedTextField jFTFValorP;
    private javax.swing.JLabel jLBLCPFP;
    private javax.swing.JLabel jLBLCodigoP;
    private javax.swing.JLabel jLBLCorP;
    private javax.swing.JLabel jLBLEntregaP;
    private javax.swing.JLabel jLBLIDPedido;
    private javax.swing.JLabel jLBLLocacao;
    private javax.swing.JLabel jLBLMidiaP;
    private javax.swing.JLabel jLBLNomeP;
    private javax.swing.JLabel jLBLQuantidadeP;
    private javax.swing.JLabel jLBLTituloP;
    private javax.swing.JLabel jLBLValorP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBFilmesP;
    private javax.swing.JTextField jTXFCorP;
    private javax.swing.JTextField jTXFIDFilmeP;
    private javax.swing.JTextField jTXFMidia;
    private javax.swing.JTextField jTXFNomeP;
    private javax.swing.JTextField jTXFPedidoID;
    private javax.swing.JTextField jTXFQuantidadeP;
    private javax.swing.JTextField jTXFTituloP;
    // End of variables declaration//GEN-END:variables
//<editor-fold defaultstate="collapsed" desc="Limite de Caracteres">

    public class CharacterLimit extends PlainDocument {

        private int iMaxLength;

        public CharacterLimit(int maxlen) {
            super();
            iMaxLength = maxlen;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {

            if (iMaxLength <= 0) // aceitara qualquer no. de caracteres  
            {
                super.insertString(offset, str, attr);
                return;
            }

            int ilen = (getLength() + str.length());
            if (ilen <= iMaxLength) // se o comprimento final for menor...  
            {
                super.insertString(offset, str, attr);   // ...aceita str  
            }
        }
    }
//</editor-fold>
}
