/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILocadora;

import SourceCodes.AutenticationCPF;
import SourceCodes.DBMetClientes;
import SourceCodes.DateConvertion;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Gian Luca
 */
public class Cad_ClienteJIF extends javax.swing.JInternalFrame {

    public String cod_escolha = null;

    /**
     * Creates new form Cad_ClienteJIF
     */
    public Cad_ClienteJIF() {
        initComponents();
        //if(jBTNPesquisar.isEnabled()==true)

        //<editor-fold defaultstate="collapsed" desc="Limite de Caracteres no TextField">
        jTXFNomeC.setDocument((Document) new CharacterLimit(100));
        jTXFBairroC.setDocument((Document) new CharacterLimit(50));
        jTXFCidadeC.setDocument((Document) new CharacterLimit(50));
        jTXFComplementoC.setDocument((Document) new CharacterLimit(100));
        jTXFDependente1.setDocument(new CharacterLimit(100));
        jTXFDependente2.setDocument(new CharacterLimit(100));
        jTXFDependente3.setDocument(new CharacterLimit(100));
        jTXFEmailC.setDocument(new CharacterLimit(50));
        jTXFIdentidadeC.setDocument(new CharacterLimit(20));
        jTXFNomeC.setDocument(new CharacterLimit(100));
        jTXFNumeroC.setDocument(new CharacterLimit(11));
        jTXFRuaC.setDocument(new CharacterLimit(100));
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPNObrigatoriosC = new javax.swing.JPanel();
        jTXFNomeC = new javax.swing.JTextField();
        jLBLNomeC = new javax.swing.JLabel();
        jLBLCPF = new javax.swing.JLabel();
        jFTFCPF = new javax.swing.JFormattedTextField();
        jTXFIdentidadeC = new javax.swing.JTextField();
        jLBLIdentidadeC = new javax.swing.JLabel();
        jLBLRuaC = new javax.swing.JLabel();
        jTXFRuaC = new javax.swing.JTextField();
        jLBLNascimentoC = new javax.swing.JLabel();
        jFTFNacimentoC = new javax.swing.JFormattedTextField();
        jTXFNumeroC = new javax.swing.JTextField();
        jLBLNumeroC = new javax.swing.JLabel();
        jFTFCEPC = new javax.swing.JFormattedTextField();
        jLBLCEPC = new javax.swing.JLabel();
        jLBLBairroC = new javax.swing.JLabel();
        jTXFBairroC = new javax.swing.JTextField();
        jTXFCidadeC = new javax.swing.JTextField();
        jLBLCidadeC = new javax.swing.JLabel();
        jLBLEstadoC = new javax.swing.JLabel();
        jCBXEstadoC = new javax.swing.JComboBox();
        jFTFTelefoneC = new javax.swing.JFormattedTextField();
        jLBLTelefoneC = new javax.swing.JLabel();
        jLBLCelularC = new javax.swing.JLabel();
        jFTFCelularC = new javax.swing.JFormattedTextField();
        jLBLComplementoC = new javax.swing.JLabel();
        jTXFComplementoC = new javax.swing.JTextField();
        jLBLEmailC = new javax.swing.JLabel();
        jTXFEmailC = new javax.swing.JTextField();
        jPNDependentesC = new javax.swing.JPanel();
        jLBLDependente1 = new javax.swing.JLabel();
        jLBLDependente2 = new javax.swing.JLabel();
        jLBLDependente3 = new javax.swing.JLabel();
        jTXFDependente1 = new javax.swing.JTextField();
        jTXFDependente2 = new javax.swing.JTextField();
        jTXFDependente3 = new javax.swing.JTextField();
        jPNBotoesC = new javax.swing.JPanel();
        jBTNSalvar = new javax.swing.JButton();
        jBTNLimpar = new javax.swing.JButton();
        jBTNPesquisar = new javax.swing.JButton();
        jBTNSair = new javax.swing.JButton();
        jBTNExcluir = new javax.swing.JButton();

        setTitle("Cadastro de Cliente");

        jPNObrigatoriosC.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Obrigatórios"));

        jTXFNomeC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFNomeC.setToolTipText("");
        jTXFNomeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTXFNomeC.setName(""); // NOI18N

        jLBLNomeC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNomeC.setText("Nome:");
        jLBLNomeC.setToolTipText("");

        jLBLCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCPF.setText("CPF:");

        jFTFCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCPF.setText("");
        jFTFCPF.setToolTipText("");
        jFTFCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFTFCPFFocusLost(evt);
            }
        });

        jTXFIdentidadeC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFIdentidadeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLIdentidadeC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLIdentidadeC.setText("Identidade:");

        jLBLRuaC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLRuaC.setText("Endereço:");

        jTXFRuaC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFRuaC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLNascimentoC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNascimentoC.setText("Nascimento:");
        jLBLNascimentoC.setToolTipText("");

        jFTFNacimentoC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFNacimentoC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFNacimentoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTXFNumeroC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFNumeroC.setToolTipText("");
        jTXFNumeroC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLNumeroC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLNumeroC.setText("Número:");

        jFTFCEPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFCEPC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCEPC.setText("");
        jFTFCEPC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLCEPC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCEPC.setText("CEP:");

        jLBLBairroC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLBairroC.setText("Bairro:");

        jTXFBairroC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFBairroC.setToolTipText("");
        jTXFBairroC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTXFCidadeC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFCidadeC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLCidadeC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCidadeC.setText("Cidade:");

        jLBLEstadoC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLEstadoC.setText("Estado:");

        jCBXEstadoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBXEstadoC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCBXEstadoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBXEstadoCActionPerformed(evt);
            }
        });

        jFTFTelefoneC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFTelefoneC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFTelefoneC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jFTFTelefoneC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFTelefoneCActionPerformed(evt);
            }
        });

        jLBLTelefoneC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLTelefoneC.setText("Telefone:");

        jLBLCelularC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLCelularC.setText("Celular:");

        jFTFCelularC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            jFTFCelularC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFCelularC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLBLComplementoC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLComplementoC.setText("Complemento:");

        jTXFComplementoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFComplementoC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLEmailC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLEmailC.setText("E-Mail:");

        jTXFEmailC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFEmailC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPNObrigatoriosCLayout = new javax.swing.GroupLayout(jPNObrigatoriosC);
        jPNObrigatoriosC.setLayout(jPNObrigatoriosCLayout);
        jPNObrigatoriosCLayout.setHorizontalGroup(
            jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                        .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                                .addComponent(jLBLTelefoneC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFTelefoneC, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLCelularC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCelularC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                                .addComponent(jLBLNumeroC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLCEPC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCEPC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLComplementoC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFComplementoC)))
                        .addGap(10, 10, 10))
                    .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                        .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                                .addComponent(jLBLRuaC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFRuaC))
                            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                                .addComponent(jLBLNomeC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFNomeC))
                            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                                .addComponent(jLBLCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLIdentidadeC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFIdentidadeC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLNascimentoC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFNacimentoC))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNObrigatoriosCLayout.createSequentialGroup()
                                .addComponent(jLBLBairroC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFBairroC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLCidadeC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTXFCidadeC, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLBLEstadoC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBXEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                        .addComponent(jLBLEmailC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFEmailC)
                        .addContainerGap())))
        );
        jPNObrigatoriosCLayout.setVerticalGroup(
            jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNObrigatoriosCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLNomeC)
                    .addComponent(jTXFNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLBLCPF)
                        .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLIdentidadeC)
                        .addComponent(jTXFIdentidadeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLBLNascimentoC)
                        .addComponent(jFTFNacimentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLRuaC)
                    .addComponent(jTXFRuaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTXFNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLNumeroC)
                    .addComponent(jLBLCEPC)
                    .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFTFCEPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLBLComplementoC)
                        .addComponent(jTXFComplementoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBXEstadoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLEstadoC)
                    .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLBLBairroC)
                            .addComponent(jTXFBairroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLBLCidadeC)
                            .addComponent(jTXFCidadeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLTelefoneC)
                    .addComponent(jFTFTelefoneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLCelularC)
                    .addComponent(jFTFCelularC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNObrigatoriosCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLEmailC)
                    .addComponent(jTXFEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPNDependentesC.setBorder(javax.swing.BorderFactory.createTitledBorder("Dependentes"));

        jLBLDependente1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLDependente1.setText("1º Dependente:");

        jLBLDependente2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLDependente2.setText("2º Dependente:");

        jLBLDependente3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLBLDependente3.setText("3º Dependente:");

        jTXFDependente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFDependente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTXFDependente2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFDependente2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTXFDependente3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTXFDependente3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPNDependentesCLayout = new javax.swing.GroupLayout(jPNDependentesC);
        jPNDependentesC.setLayout(jPNDependentesCLayout);
        jPNDependentesCLayout.setHorizontalGroup(
            jPNDependentesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNDependentesCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNDependentesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNDependentesCLayout.createSequentialGroup()
                        .addComponent(jLBLDependente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFDependente1))
                    .addGroup(jPNDependentesCLayout.createSequentialGroup()
                        .addComponent(jLBLDependente3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFDependente3))
                    .addGroup(jPNDependentesCLayout.createSequentialGroup()
                        .addComponent(jLBLDependente2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTXFDependente2)))
                .addContainerGap())
        );
        jPNDependentesCLayout.setVerticalGroup(
            jPNDependentesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNDependentesCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNDependentesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBLDependente1)
                    .addComponent(jTXFDependente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNDependentesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLDependente2)
                    .addComponent(jTXFDependente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNDependentesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBLDependente3)
                    .addComponent(jTXFDependente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPNBotoesC.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBTNSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Save.png"))); // NOI18N
        jBTNSalvar.setText("Salvar");
        jBTNSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNSalvarMouseClicked(evt);
            }
        });

        jBTNLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Clear.png"))); // NOI18N
        jBTNLimpar.setText("Limpar");
        jBTNLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNLimparMouseClicked(evt);
            }
        });

        jBTNPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Find.png"))); // NOI18N
        jBTNPesquisar.setText("Pesquisar");
        jBTNPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNPesquisarActionPerformed(evt);
            }
        });

        jBTNSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Cancel.png"))); // NOI18N
        jBTNSair.setText("Fechar");
        jBTNSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNSairActionPerformed(evt);
            }
        });

        jBTNExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Delete.png"))); // NOI18N
        jBTNExcluir.setText("Excluir");
        jBTNExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBTNExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPNBotoesCLayout = new javax.swing.GroupLayout(jPNBotoesC);
        jPNBotoesC.setLayout(jPNBotoesCLayout);
        jPNBotoesCLayout.setHorizontalGroup(
            jPNBotoesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNBotoesCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTNSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTNSair)
                .addContainerGap())
        );
        jPNBotoesCLayout.setVerticalGroup(
            jPNBotoesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNBotoesCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNBotoesCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTNSalvar)
                    .addComponent(jBTNLimpar)
                    .addComponent(jBTNPesquisar)
                    .addComponent(jBTNSair)
                    .addComponent(jBTNExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPNObrigatoriosC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPNDependentesC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPNBotoesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPNObrigatoriosC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPNDependentesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPNBotoesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        setBounds(0, 0, 663, 522);
    }// </editor-fold>//GEN-END:initComponents

    private void jCBXEstadoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBXEstadoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBXEstadoCActionPerformed

    private void jFTFTelefoneCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFTelefoneCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFTelefoneCActionPerformed

    private void jBTNSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNSalvarMouseClicked
        DBMetClientes cad_Client = new DBMetClientes();
        System.out.println(cod_escolha);
        cad_Client.setNome(jTXFNomeC.getText());
        cad_Client.setEmail(jTXFEmailC.getText());
        cad_Client.setCpf(jFTFCPF.getText().replace("-", "").replace(".", ""));
        cad_Client.setIdentidade(jTXFIdentidadeC.getText());
        cad_Client.setNascimento(jFTFNacimentoC.getText());
        cad_Client.setNumero(jTXFNumeroC.getText());
        cad_Client.setCep(jFTFCEPC.getText().replace("-", ""));
        cad_Client.setTelefone(jFTFTelefoneC.getText());
        cad_Client.setCelular(jFTFCelularC.getText());
        cad_Client.setLogradouro(jTXFRuaC.getText());
        cad_Client.setComplemento(jTXFComplementoC.getText());
        cad_Client.setBairro(jTXFBairroC.getText());
        cad_Client.setCidade(jTXFCidadeC.getText());
        cad_Client.setEstado(jCBXEstadoC.getSelectedItem().toString());
        cad_Client.setDependente1(jTXFDependente1.getText());
        cad_Client.setDependente2(jTXFDependente2.getText());
        cad_Client.setDependente3(jTXFDependente3.getText());
        if (cod_escolha == null) {
            cad_Client.Cadastrar();
        } else {
            cad_Client.Alterar(cod_escolha);
        }
        jTXFNomeC.setText("");
        jTXFEmailC.setText("");
        jFTFCPF.setText("");
        jTXFIdentidadeC.setText("");
        jFTFNacimentoC.setText("");
        jTXFNumeroC.setText("");
        jFTFCEPC.setText("");
        jFTFTelefoneC.setText("");
        jFTFCelularC.setText("");
        jTXFRuaC.setText("");
        jTXFComplementoC.setText("");
        jTXFBairroC.setText("");
        jTXFCidadeC.setText("");
        jTXFDependente1.setText("");
        jTXFDependente2.setText("");
        jTXFDependente3.setText("");
    }//GEN-LAST:event_jBTNSalvarMouseClicked

    private void jBTNLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNLimparMouseClicked
        jTXFNomeC.setText("");
        jTXFEmailC.setText("");
        jFTFCPF.setText("");
        jTXFIdentidadeC.setText("");
        jFTFNacimentoC.setText("");
        jTXFNumeroC.setText("");
        jFTFCEPC.setText("");
        jFTFTelefoneC.setText("");
        jFTFCelularC.setText("");
        jTXFRuaC.setText("");
        jTXFComplementoC.setText("");
        jTXFBairroC.setText("");
        jTXFCidadeC.setText("");
        jTXFDependente1.setText("");
        jTXFDependente2.setText("");
        jTXFDependente3.setText("");
        cod_escolha = null;
        jBTNSalvar.setText("Salvar");
    }//GEN-LAST:event_jBTNLimparMouseClicked

    private void jBTNSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNSairActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "Sair da Tela", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jBTNSairActionPerformed

    private void jBTNExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNExcluirMouseClicked
        cod_escolha = JOptionPane.showInputDialog("Digite o Código referente ao Cliente que deseja excluir:").replace(".", "").replace("-", "");
        DBMetClientes cad_Client = new DBMetClientes();
        cad_Client.exluir(cod_escolha);
    }//GEN-LAST:event_jBTNExcluirMouseClicked

    private void jFTFCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFTFCPFFocusLost
        AutenticationCPF autenticacao = new AutenticationCPF();
        autenticacao.MudarCaracter(jFTFCPF.getText());
        if (autenticacao.ValidaCPF() == false) {
            JOptionPane.showMessageDialog(null, "CPF inválido.");
            jFTFCPF.setText("");
        }

    }//GEN-LAST:event_jFTFCPFFocusLost

    private void jBTNPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNPesquisarActionPerformed
        cod_escolha = JOptionPane.showInputDialog("Digite o Código referente ao Cliente que deseja pesquisar:").replace(".", "").replace("-", "");
        DBMetClientes Alterar = new DBMetClientes();
        Alterar.mostrar(cod_escolha);
        jTXFNomeC.setText(Alterar.getNome());
        jTXFEmailC.setText(Alterar.getEmail());
        jFTFCPF.setText(Alterar.getCpf());
        jTXFIdentidadeC.setText(Alterar.getIdentidade());
        jFTFNacimentoC.setText(Alterar.getNascimento());
        jTXFNumeroC.setText(Alterar.getNumero());
        jFTFCEPC.setText(Alterar.getCep());
        jFTFTelefoneC.setText(Alterar.getTelefone());
        jFTFCelularC.setText(Alterar.getCelular());
        jTXFRuaC.setText(Alterar.getLogradouro());
        jTXFComplementoC.setText(Alterar.getComplemento());
        jTXFBairroC.setText(Alterar.getBairro());
        jTXFCidadeC.setText(Alterar.getCidade());
        jTXFDependente1.setText(Alterar.getDependente1());
        jTXFDependente2.setText(Alterar.getDependente2());
        jTXFDependente3.setText(Alterar.getDependente3());
        jCBXEstadoC.setSelectedItem(Alterar.getEstado());
        jBTNSalvar.setText("Alterar");

        //**********************************************

    }//GEN-LAST:event_jBTNPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNExcluir;
    private javax.swing.JButton jBTNLimpar;
    private javax.swing.JButton jBTNPesquisar;
    private javax.swing.JButton jBTNSair;
    private javax.swing.JButton jBTNSalvar;
    private javax.swing.JComboBox jCBXEstadoC;
    private javax.swing.JFormattedTextField jFTFCEPC;
    private javax.swing.JFormattedTextField jFTFCPF;
    private javax.swing.JFormattedTextField jFTFCelularC;
    private javax.swing.JFormattedTextField jFTFNacimentoC;
    private javax.swing.JFormattedTextField jFTFTelefoneC;
    private javax.swing.JLabel jLBLBairroC;
    private javax.swing.JLabel jLBLCEPC;
    private javax.swing.JLabel jLBLCPF;
    private javax.swing.JLabel jLBLCelularC;
    private javax.swing.JLabel jLBLCidadeC;
    private javax.swing.JLabel jLBLComplementoC;
    private javax.swing.JLabel jLBLDependente1;
    private javax.swing.JLabel jLBLDependente2;
    private javax.swing.JLabel jLBLDependente3;
    private javax.swing.JLabel jLBLEmailC;
    private javax.swing.JLabel jLBLEstadoC;
    private javax.swing.JLabel jLBLIdentidadeC;
    private javax.swing.JLabel jLBLNascimentoC;
    private javax.swing.JLabel jLBLNomeC;
    private javax.swing.JLabel jLBLNumeroC;
    private javax.swing.JLabel jLBLRuaC;
    private javax.swing.JLabel jLBLTelefoneC;
    private javax.swing.JPanel jPNBotoesC;
    private javax.swing.JPanel jPNDependentesC;
    private javax.swing.JPanel jPNObrigatoriosC;
    private javax.swing.JTextField jTXFBairroC;
    private javax.swing.JTextField jTXFCidadeC;
    private javax.swing.JTextField jTXFComplementoC;
    private javax.swing.JTextField jTXFDependente1;
    private javax.swing.JTextField jTXFDependente2;
    private javax.swing.JTextField jTXFDependente3;
    private javax.swing.JTextField jTXFEmailC;
    private javax.swing.JTextField jTXFIdentidadeC;
    private javax.swing.JTextField jTXFNomeC;
    private javax.swing.JTextField jTXFNumeroC;
    private javax.swing.JTextField jTXFRuaC;
    // End of variables declaration//GEN-END:variables

//<editor-fold defaultstate="collapsed" desc="Limite de Caracteres">
    public class CharacterLimit extends PlainDocument {

        private int iMaxLength;

        public CharacterLimit(int maxlen) {
            super();
            iMaxLength = maxlen;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {

            if (iMaxLength <= 0) // aceitara qualquer no. de caracteres  
            {
                super.insertString(offset, str, attr);
                return;
            }

            int ilen = (getLength() + str.length());
            if (ilen <= iMaxLength) // se o comprimento final for menor...  
            {
                super.insertString(offset, str, attr);   // ...aceita str  
            }
        }
    }
//</editor-fold>

}
