/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILocadora;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.Timer;

/**
 *
 * @author Gian Luca
 */
public class MainPageAdminJFM extends javax.swing.JFrame {

    /**
     * Creates new form MainPageJMF
     */
    public MainPageAdminJFM() {
        initComponents();
        //setSize(minhaLargura, minhaAltura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDKPAdmin = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLBLDate = new javax.swing.JLabel();
        jLBLTime = new javax.swing.JLabel();
        jMBPrincipal = new javax.swing.JMenuBar();
        jMBArquivos = new javax.swing.JMenu();
        jMIDeslogar = new javax.swing.JMenuItem();
        jMISair = new javax.swing.JMenuItem();
        jMICadastro = new javax.swing.JMenu();
        jMICliente = new javax.swing.JMenuItem();
        jMIFilmes = new javax.swing.JMenuItem();
        jMIFuncionarios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMIFichaFilme = new javax.swing.JMenuItem();
        jMIFichaCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Adm");
        setMinimumSize(new java.awt.Dimension(900, 720));
        setPreferredSize(new java.awt.Dimension(900, 625));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 700));

        jDKPAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jDKPAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jDKPAdmin.setPreferredSize(new java.awt.Dimension(900, 635));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Wileecoyte.gif"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jDKPAdminLayout = new javax.swing.GroupLayout(jDKPAdmin);
        jDKPAdmin.setLayout(jDKPAdminLayout);
        jDKPAdminLayout.setHorizontalGroup(
            jDKPAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jDKPAdminLayout.setVerticalGroup(
            jDKPAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        jDKPAdmin.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLBLDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLBLDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBLDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLBLTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLBLTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBLTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jDKPAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLBLTime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBLDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDKPAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLBLDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBLTime, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMBArquivos.setText("Locadora");

        jMIDeslogar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMIDeslogar.setText("Deslogar");
        jMIDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDeslogarActionPerformed(evt);
            }
        });
        jMBArquivos.add(jMIDeslogar);

        jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMISair.setText("Sair");
        jMISair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMISairMouseClicked(evt);
            }
        });
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMBArquivos.add(jMISair);

        jMBPrincipal.add(jMBArquivos);

        jMICadastro.setText("Cadastro");

        jMICliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMICliente.setText("Clientes");
        jMICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteActionPerformed(evt);
            }
        });
        jMICadastro.add(jMICliente);

        jMIFilmes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMIFilmes.setText("Filmes");
        jMIFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFilmesActionPerformed(evt);
            }
        });
        jMICadastro.add(jMIFilmes);

        jMIFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMIFuncionarios.setText("Funcionários");
        jMIFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFuncionariosActionPerformed(evt);
            }
        });
        jMICadastro.add(jMIFuncionarios);

        jMBPrincipal.add(jMICadastro);

        jMenu5.setText("Fichas");

        jMIFichaFilme.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIFichaFilme.setText("Filme");
        jMIFichaFilme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMIFichaFilmeMouseClicked(evt);
            }
        });
        jMIFichaFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFichaFilmeActionPerformed(evt);
            }
        });
        jMenu5.add(jMIFichaFilme);

        jMIFichaCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMIFichaCliente.setText("Cliente");
        jMIFichaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFichaClienteActionPerformed(evt);
            }
        });
        jMenu5.add(jMIFichaCliente);

        jMBPrincipal.add(jMenu5);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //this.setExtendedState(MAXIMIZED_BOTH);
        String diaSemana[] = {"domingo", "segunda-feira",
            "terça-feira", "quarta-feira",
            "quinta-feira", "sexta-feira",
            "sábado"};

        String meses[] = {"janeiro", "fevereiro", "março",
            "abril", "maio", "junho", "julho",
            "agosto", "setembro", "outubro",
            "novembro", "dezembro"};

        Calendar agora = Calendar.getInstance();
        int ho = agora.get(Calendar.HOUR_OF_DAY);
        int mi = agora.get(Calendar.MINUTE);
        int se = agora.get(Calendar.SECOND);

        int ds = agora.get(Calendar.DAY_OF_WEEK);
        int dia = agora.get(Calendar.DAY_OF_MONTH);
        int mes = agora.get(Calendar.MONTH);
        int ano = agora.get(Calendar.YEAR);

        jLBLTime.setText(formatar(ho % 12) + ":" + formatar(mi) + ":" + formatar(se) + "");
        jLBLDate.setText(diaSemana[ds - 1] + ", " + formatar(dia) + " de " + meses[mes] + " de " + ano + "");
    }//GEN-LAST:event_formWindowOpened

    private void jMIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteActionPerformed
        Cad_ClienteJIF Cad_Cliente = new Cad_ClienteJIF();
        jDKPAdmin.add(Cad_Cliente);
        Cad_Cliente.setVisible(true);
    }//GEN-LAST:event_jMIClienteActionPerformed

    private void jMIFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFilmesActionPerformed
        Cad_FilmeJIF Cad_Filme = new Cad_FilmeJIF();
        jDKPAdmin.add(Cad_Filme);
        Cad_Filme.setVisible(true);
    }//GEN-LAST:event_jMIFilmesActionPerformed

    private void jMIFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFuncionariosActionPerformed
        Cad_FuncionarioJIF Cad_Funcionario = new Cad_FuncionarioJIF();
        jDKPAdmin.add(Cad_Funcionario);
        Cad_Funcionario.setVisible(true);
    }//GEN-LAST:event_jMIFuncionariosActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","Sair da Tela",javax.swing.JOptionPane.YES_NO_OPTION )==0){  
            this.dispose();
        }
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMISairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMISairMouseClicked
        
    }//GEN-LAST:event_jMISairMouseClicked

    private void jMIFichaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFichaClienteActionPerformed
        Ficha_ClienteJIF ficha_cliente = new Ficha_ClienteJIF();
        jDKPAdmin.add(ficha_cliente);
        ficha_cliente.setVisible(true);
    }//GEN-LAST:event_jMIFichaClienteActionPerformed

    private void jMIFichaFilmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMIFichaFilmeMouseClicked
        
    }//GEN-LAST:event_jMIFichaFilmeMouseClicked

    private void jMIDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDeslogarActionPerformed
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Deslogar?","Trocar o usuário",javax.swing.JOptionPane.YES_NO_OPTION )==0){  
            this.dispose();
            StartPageJFM login_page = new StartPageJFM();
            login_page.setVisible(true);
        }
        
    }//GEN-LAST:event_jMIDeslogarActionPerformed

    private void jMIFichaFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFichaFilmeActionPerformed
        Ficha_FilmeJIF ficha_filme = new Ficha_FilmeJIF();
        jDKPAdmin.add(ficha_filme);
        ficha_filme.setVisible(true);
    }//GEN-LAST:event_jMIFichaFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageAdminJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageAdminJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageAdminJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageAdminJFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainPageAdminJFM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDKPAdmin;
    private javax.swing.JLabel jLBLDate;
    private javax.swing.JLabel jLBLTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMBArquivos;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMICadastro;
    private javax.swing.JMenuItem jMICliente;
    private javax.swing.JMenuItem jMIDeslogar;
    private javax.swing.JMenuItem jMIFichaCliente;
    private javax.swing.JMenuItem jMIFichaFilme;
    private javax.swing.JMenuItem jMIFilmes;
    private javax.swing.JMenuItem jMIFuncionarios;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private String formatar(int num) {
        DecimalFormat df = new DecimalFormat("00");
        return df.format(num);
    }
    //<editor-fold defaultstate="collapsed" desc="Tamanho automático de tela.">
    Toolkit kit = Toolkit.getDefaultToolkit();
    Dimension tamTela = kit.getScreenSize();
    int larg = tamTela.width; 
    int alt = tamTela.height;
    int minhaLargura = (int) (larg * 0.472);
    int minhaAltura = (int) (alt * 0.730);
    //</editor-fold>
}
